spring.application.name=api-gateway
server.port=8080

# Route to Train Search Service
spring.cloud.gateway.routes[0].id=train-search-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/trains/**

# Route to PNR Service
spring.cloud.gateway.routes[1].id=pnr-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pnr/**

# Route to Alert Service
spring.cloud.gateway.routes[2].id=alert-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/alerts/**

# Actuator
management.endpoints.web.exposure.include=health,info