spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=train-search-service
spring.cloud.gateway.routes[0].uri=${TRAIN_SEARCH_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/trains/**

spring.cloud.gateway.routes[1].id=pnr-service
spring.cloud.gateway.routes[1].uri=${PNR_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pnr/**

spring.cloud.gateway.routes[2].id=alert-service
spring.cloud.gateway.routes[2].uri=${ALERT_SERVICE_URL}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/alerts/**

management.endpoints.web.exposure.include=health,info