spring.application.name=pnr-service
server.port=8082

spring.data.mongodb.uri=mongodb+srv://elizabetheldhose001_db_user:scxketJ36DvVy1f3@cluster0.0fnjabn.mongodb.net/railsmart_pnr?retryWrites=true&w=majority&appName=Cluster0

management.endpoints.web.exposure.include=health,info   