spring.application.name=train-search-service
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb+srv://elizabetheldhose001_db_user:scxketJ36DvVy1f3@cluster0.0fnjabn.mongodb.net/railsmart_trains?retryWrites=true&w=majority&appName=Cluster0


# Actuator
management.endpoints.web.exposure.include=health,info