spring.application.name=train-search-service
server.port=8081

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Actuator
management.endpoints.web.exposure.include=health,info

# Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379